const menu = {
    item17: { name: "Garlic Bread", cost: 50, category: "Appetizers" },
    item18: { name: "Crispy Chicken", cost: 120, category: "Appetizers" },
    item19: { name: "Buttern Nan", cost: 60, category: "Appetizers" },
    item20: { name: "Steamed Momos", cost: 100, category: "Appetizers" },
    item1: { name: "Sandwich", cost: 100, category: "Snacks" },
    item4: { name: "Panipuri", cost: 100, category: "Snacks" },
    item2: { name: "Burger", cost: 150, category: "Snacks" },
    item3: { name: "Momos", cost: 150, category: "Snacks" },
    item5: { name: "French Fries", cost: 105, category: "Entree" },
    item8: { name: "Spring Rolls", cost: 80, category: "Entree" },
    item6: { name: "Chicken Lollipop", cost: 150, category: "Entree" },
    item7: { name: "Meet Majestics", cost: 200, category: "Entree" },
    item9: { name: "Vegetable Noodles", cost: 180, category: "Main Course" },
    item12: { name: "Veg Fried Rice", cost: 160, category: "Main Course" },
    item10: { name: "Mixed Biryani", cost: 250, category: "Main Course" },
    item11: { name: "Chicken Biryani", cost: 270, category: "Main Course" },
    item13: { name: "Apple Pie", cost: 90, category: "Desserts" },
    item14: { name: "Flavoured Icecreams", cost: 120, category: "Desserts" },
    item15: { name: "Chocolate Cake", cost: 105, category: "Desserts" },
    item16: { name: "Icecream Cake", cost: 130, category: "Desserts" },
    item21: { name: "ThumsUp", cost: 45, category: "Beverages" },
    item22: { name: "Iced Tea", cost: 55, category: "Beverages" },
    item23: { name: "Lemonade", cost: 50, category: "Beverages" },
    item24: { name: "Mocktails", cost: 70, category: "Beverages" }
};
